version: '2.2'
services:
  jaeger-singleton:
    image: jaegertracing/all-in-one:1.14
    container_name: jaeger-singleton
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    networks:
      - local-net
networks:
  local-net:
    external: true